[package]
name = "autogen"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.29"
tokio = { version = "1.35.1", features = ["full"] }
tracing = "0.1.40"
tokio-util = "0.7.10"

[dev-dependencies]
async-std = "1.12.0"
